### ISSUE TITLE
Out Module missing format width exception

### ISSUE THREAD

**Issue by luarockr** [lboasso/oberonc#2]
Trying to print an Integer with 

    MODULE OutInt;
  
    IMPORT Out;

    BEGIN
      Out.Int(10, 0); Out.Ln;
    END OutInt.

gives exception

Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.util.MissingFormatWidthException: %0d
	at java.util.Formatter$FormatSpecifier.checkNumeric(Formatter.java:3022)
	at java.util.Formatter$FormatSpecifier.checkInteger(Formatter.java:2982)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2729)
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.io.PrintStream.format(PrintStream.java:970)
	at java.io.PrintStream.printf(PrintStream.java:871)
	at Out.Int(Out.java:22)
	at OutInt.<clinit>(OutInt.Mod:6)

Not sure if this is actually defined anywhere, values other than 0 work here, but so far I am used to use 0 from Oxford and Vishaps Oberon compilers.

**Comment by luarockr** [comment]
a different number than 0 works.

**Comment by lboasso** [comment]
Thank you again for reporting this bug, you help is very much appreciated!
Your example should work, I fixed the bug in commit 8440be0596a60ec5fb5b437ca96f151a2a4f9727
